### ISSUE TITLE
Emit name parts

### ISSUE THREAD

**Issue by justincy** [genxtract/genxtract#47]
Extractors should be able to emit names in pieces, as opposed to always emitting full name strings. Sometimes the names are already in pieces on the site. The extractor, with local knowledge, will always know better how to split the name into pieces. Forcing the extractor to combine the name and expecting the combinator to subsequently split the name again is bound to produce errors. Otherwise the combinators would have to know that on Find-A-Grave nicknames are in quotes and on MyHeritage maiden names are in parenthesis.

Formal proposal:

```
emit.NameParts({
    person: personId,
    // At least one part is required
    // All parts are strings
    parts: {
        prefix,
        given,
        surname,
        suffix
    }
})
```

**Comment by jonnymbgood** [comment]
As another option, what do you think about augmenting `emit.name`?
````javascript
emit.name({
person,
name,
surname,
given,
...
});
````
Then the combinator could check for the existence of things like surname, and if absent, would default to using the name value itself.

Thoughts?

**Comment by justincy** [comment]
It's pretty much the same. The current spec seems to be very explicit about everything so that's why I proposed a new emitter type. I don't see how augmenting `name` has any benefit.

Do we call them emitter events, emitter methods, or emitter types?

**Comment by justincy** [comment]
I just pushed a possible implementation for this. See how it's handled in the [GedcomX combinator](https://github.com/genxtract/genxtract/blob/6f8976e0eccd0f351325f26efaa1316aeeab4d16/packages/gedcomx/src/GedcomX.js#L122-L134). I pushed a lot of functionality into `nameParts()` and left `name()` with basically just splitting the full string. That leads me to wonder if the name splitting ought to be there; that particular method of splitting doesn't seem like it'd be isolated to just GedcomX. @jonnymbgood perhaps this is part of why you proposed just augmenting `name()`?

**Comment by jonnymbgood** [comment]
IMO it keeps things simpler, especially if we view the key `name` as analogous to `full name`. As to the specificity, we are ultimately describing a name. And we have plenty of other emitter types that have optional keys (date and place are optional on everything i believe)

To sum up, my vote is to augment `Name`, since that is what we are emitting on both cases. If we start emitting name parts, then a name part becomes a first class citizen. I'm a bit uncomfortable with that.

**Comment by jonnymbgood** [comment]
Question: if we emit a single `NamePart`, would we also emit a `Name`? It seems to me that they are the same thing.

**Comment by justincy** [comment]
> IMO it keeps things simpler, especially if we view the key name as analogous to full name.

That makes sense. In my mind they were two separate tasks.

**Comment by justincy** [comment]
Let me expound on my last comment. I imagined that `NameParts()` wasn't a way to make `NamePart` a first class citizen but was an alternate way of describing a `Name`. In other words, you would either send the full text of send it in pieces. So when I saw your proposal I didn't see any added benefit because it looked to me as just overloading one method for two totally distinct use cases. But I see now that there's value in being able to specify both the full text and the parts at the same time.

**Comment by jonnymbgood** [comment]
Ah, as an alternative to `Name`. That makes sense. So now that we've established that `Name` and `NamePart` are both describing `Name`, how do you feel about adding some keys to `Name` that are optional?

**Comment by justincy** [comment]
I'm playing with it right now. The code in the combinators won't be as clean but I think I can stomach it.

**Comment by jonnymbgood** [comment]
Yeah.

Also, I've been playing with the idea of putting the name splitting code into the emitter, but it doesn't feel right. It should probably stay in the combinator. That way there is no interference between the extractor and the combinator.
