### ISSUE TITLE
Subtype events or make them 1st level entities?

### ISSUE THREAD

**Issue by justincy** [genxtract/genxtract#6]
We're discussing whether to have events be subtyped or 1st-level entities in the spec. Consider these examples:

__Subtyped:__

```js
{
  "events": [{
    type: "Birth",
    date: "1909-01-01",
    place: "Hometown"
  }]
}
```

__1st level__:

```js
{
  "birth": [{
    date: "1909-01-01",
    place: "Hometown"
  }]
}
```

The same issue applies to roles (whether to list them generically in an array or to be explicit properties on each event).

**Comment by justincy** [comment]
Quoting @jonnymbgood:

> I also thought about having sub types, and I realized why it makes me uncomfortable. You can't extend subtypes with additional information very easily. If you wanted to associate a midwife with a birth but it was a generic event, then you need to create a generic relationship subtype. And if you want to record a birth weight, now you need to support a generic fact on the generic event. At that point everything is generic and subtyped.

**Comment by justincy** [comment]
Those points are very valid. The spec needs to allow additional information. The spec should support any genealogically significant information.

If the bounds of our domain (genealogically significant information) were known and reasonable in size then I'd be in favor of a more explicit spec. But the bounds aren't known. The bounds of genealogically significant information are huge.

Let's consider what happens when we need to amend the spec to support a new event type: Election. We'll consider a few aspects of the spec change:

1. The perspective of a developer
2. The application's ability to use new data
3. The application's ability to ignore new data
4. The application's ability to save and export the new data even if it's ignored

If we want to be explicit and have no subtypes then Election becomes a new 1st level entity, and now we just changed our data format. That's painful for developers. If I want to display that new type then at the very least I have to modify my parser and add new UI elements (I feel like I'm really underestimating that work). I can choose to ignore it (my parser shouldn't fail) but I can't save it because I'm not parsing it (and I don't know what it is) and thus I'm unable to pass that data long.

If events are typed and roles are typed then our spec is amended to list Election as a known event type. The data format hasn't changed. If developers choose to use the data then they just update an enum and choose a display string for the new type. Events are generic so they also have generic UI elements that just work with the new type and display string. If developers decide they don't care about Election events they can still save and export that data without modifying their parser or serializer.

Imagine what happens when we add places. That is a nightmare both as a spec maintainer and a developer.

**Comment by jonnymbgood** [comment]
Based on the face-to-face discussions we have been having, First level events are the way to go for the extractors. There is a discreet set of allowed events/facts, and each has a set of allowable properties. To facilitate extractor development and to reduce errors, there is an Emit class that contains 1 function per event/fact/etc. Basic checking is performed, and only valid dat events are emitted. This also serves to document the possible set of events/facts/etc...
